name: SPS Publish

on:
  workflow_dispatch:
  push:
    branches:
      - publish
  repository_dispatch:
    types:
      - sps_digital_garden_updated

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      THEME: "twilight"
      SPS_DG_PATH: "./sps-digital-garden"

    steps:
      - name: Prepare Dynamic Environment Variables
        run: |
          echo "BUILD_PATH=./astro-theme-${{ env.THEME }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: 'publish'
          path: ${{ env.BUILD_PATH }}

      - name: Checkout sps-digital-garden
        uses: actions/checkout@v4
        with:
          repository: SPSZerone/sps-digital-garden
          ref: 'main'
          path: ${{ env.SPS_DG_PATH }}
          token: ${{ secrets.SPS_DG_PUBLISH_PAT }}

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3
        with:
          nu-version: '0.112.2'

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: '${{ env.SPS_DG_PATH }}/go/go.mod'
          # go-version: '1.26.x'
          cache: true

      - name: "SPS Digital Garden -> scripts/publish.nu"
        run: nu ${{ env.SPS_DG_PATH }}/scripts/publish.nu -s astro -t ${{ env.THEME }} -p ${{ env.BUILD_PATH }}

      - name: Install, build, and upload your site
        uses: withastro/action@v5
        with:
          package-manager: pnpm@10.33.0
          build-cmd: pnpm run build
          path: ${{ env.BUILD_PATH }}
        # env:
          # PUBLIC_POKEAPI: 'https://pokeapi.co/api/v2' # 对变量值使用单引号。（可选）

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
